---
triple:          'x86_64-apple-darwin'
binary-path:     '/Users/brettmorrison/Desktop/Vigenere Cipher/app'
relocations:
  - { offset: 0x26, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100000D90, symSize: 0x90 }
  - { offset: 0x3F, size: 0x8, addend: 0x0, symName: _alphabet, symObjAddr: 0x1C0, symBinAddr: 0x100002000, symSize: 0x0 }
  - { offset: 0x6E, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100000D90, symSize: 0x90 }
  - { offset: 0xC0, size: 0x8, addend: 0x0, symName: _map_message, symObjAddr: 0x90, symBinAddr: 0x100000E20, symSize: 0xC0 }
  - { offset: 0x13C, size: 0x8, addend: 0x0, symName: _map_to_int, symObjAddr: 0x150, symBinAddr: 0x100000EE0, symSize: 0x64 }
...
